### PR TITLE
MadryEtAl tutorial

### PR DESCRIPTION
**Pull request by AngusG**
Similar to `mnist_tutorial_tf.py` only using MadryEtAl attack

### CODE REVIEW

**Comment by goodfeli** [comment]
Hi Angus,
Please write to cleverhans-dev before starting work on new features, to make sure you spend time only on features we plan to merge. We do not want to create more tutorials for each attack, because it is a large amount of duplicated code to maintain and test.
-Ian

**Comment by goodfeli** [comment]
If you'd like to work on something like a generic trainer script or a generic attack script that can run attacks on a saved model, that could be configured to give results for the Madry attack. Please free free to discuss further on cleverhans-dev.

**Comment by AngusG** [comment]
Hi Ian, that sounds like a good idea. I already have something like a generic attack script I could share. I will note to communicate on cleverhans-dev for next time.

**Comment by npapernot** [comment]
Thank you Angus!

**Pull request closed without merging**
