### PR TITLE
Make CarliniWagner tutorial more general, use source_samples flag

### PR DESCRIPTION
**Pull request by AngusG**
The `source_samples` flag wasn't being used in the CarliniWagner tutorial, this PR attempts to make the tutorial more reasonable for various settings of the `viz_enabled`,`targeted`, and `source_samples` `FLAGS`. Magic numbers have also been replaced with the relevant variables where appropriate.

### CODE REVIEW

**Comment by AngusG** [comment]
The failed test for Python 2.7/TensorFlow 1.1.0 appears to be related to #17.

**Comment by npapernot** [comment]
Thanks for the PR, it looks mostly good. I would suggest one change though: right now when the attack is untargeted, the code is using the grid visualization. It would most likely make more sense to just display them with the `pair_visual` function from https://github.com/tensorflow/cleverhans/blob/master/cleverhans/utils.py#L150. Otherwise, I fear the grid may mislead users into thinking that the attack was targeted.

**Comment by AngusG** [comment]
Thanks for the feedback. I actually think that the grid visualisation is reasonable for the untargeted case as shown in the following screenshot (one adversarial per corresponding clean image). I was thinking we could do something similar to the `mnist_tutorial_jsma.py` where pair_visual is used as an animation, but the adversarials are computed in a batch for the cw tutorial as opposed to one at a time so I wasn't sure it made sense here. 

cleverhans _grid_visualization

**Comment by npapernot** [comment]
I see your point. That makes sense. Could you share a screenshot of the whole matplotlib window to double check how it renders?

**Comment by AngusG** [comment]
Here's a screenshot:

cleverhans _grid_visualization_screenshot_untargeted

**Comment by npapernot** [comment]
Perfect, thanks for sending this out.

**Pull request merged**
