### PR TITLE
Add libgcc to conda install to address issue 339

### PR DESCRIPTION
**Pull request by catherio**
This might fix the ligstdc++.so.6 issue we see #339. I can't repro locally, so just gonna see if the build turns up green.

### CODE REVIEW

**Comment by npapernot** [comment]
Thanks Catherine! Feel free to ping me directly if you need someone to look at it / LGTM once the tests turn green.

**Comment by catherio** [comment]
@npapernot This would be faster if we had https://docs.travis-ci.com/user/running-build-in-debug-mode/ enabled. Is there a reason not to?

**Comment by npapernot** [comment]
I think there is no reason for us to not use this debug mode because the potential security threats are not really a risk for our project. Let me email the Travis support to ask them to enable this feature for future needs. Note that according to the documentation, debug mode is limited to those with push access, which includes you.

**Comment by catherio** [comment]
The build won't be happy unless I fix both issue #339 and issue #340 at once, so I'm closing this and submitting one PR for both.

**Pull request closed without merging**
