### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by rzhe97**
Punctuation mistake

### CODE REVIEW

**Comment by rzhe97** [comment]
I signed it!

**Comment by goodfeli** [comment]
Looks like an update to Cloud broke the build. I'm fixing it here: https://github.com/tensorflow/cleverhans/pull/482

**Comment by goodfeli** [comment]
The build is fixed now. I restarted the build for this PR.

**Comment by goodfeli** [comment]
I think not, just trying to get the tests to pass

**Comment by rzhe97** [comment]
Okay, thanks and have a nice day.

**Comment by this8is8mine8** [comment]
Okay, enjoy yourself

**Pull request merged**
