### PR TITLE
Consistent naming scheme across attacks

### PR DESCRIPTION
**Pull request by aidangomez**
WIP

### CODE REVIEW

**Comment by npapernot** [comment]
I think it would make sense to discuss this change on the cleverhans-dev mailing list first because it would be a major API change

**Comment by npapernot** [comment]
(just to be clear, I think coming up with an unified terminology for the different attack parameters is a good idea and would be beneficial to the community if done based on a consensus)

**Comment by goodfeli** [comment]
I think the result of the discussion on the mailing list was that we're OK with it, right @npapernot ?
However, the PEP8 tests are currently failing, because some lines are too long now.

**Comment by npapernot** [comment]
Yes there were no objections on the mailing list so we are good to proceed with the change

**Comment by npapernot** [comment]
@aidangomez any updates?

**Comment by aidangomez** [comment]
@npapernot sorry, super preoccupied with work at the moment. Will return to this shortly.

**Comment by npapernot** [comment]
Ping @aidangomez ?

**Comment by aidangomez** [comment]
Okay so since the diffs are unreadable here is what has been changed:
  - nb_iters -> step_count
  - eps_iter -> step_size
  - epsilon -> eps (or eps_iter depending on the intended use)
  - 2 space indent following the Tensorflow style guide

**Comment by npapernot** [comment]
Thanks for making the changes @aidangomez 

I talked about this offline w/ @goodfeli. We'd rather avoid merging such a large PR right before ICLR so we'll hold on this for another 2 weeks.

It would also be cleaner for the history to make two different PRs: one that changes to 2 space indents and one that changes the names. Would you be able to work on that after ICLR or should I take care of it?

**Comment by aidangomez** [comment]
@npapernot Hmm so I was thinking about this and maybe we should create a decorator that warns when someone is using an deprecated name?

**Comment by npapernot** [comment]
SGTM, will check in after ICLR

**Comment by goodfeli** [comment]
Let's close this PR for now. After the ICLR deadline passes, let's do one mega-PR that changes all the whitespace. After that, let's redo the other changes proposed here.

**Pull request closed without merging**
