### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by goodfeli**

### CODE REVIEW

**Comment by catherio** [comment]
This build failure looks spurious. Going to try closing and re-opening the pull request to re-run the build.

**Comment by goodfeli** [comment]
You can also log in to travis to restart individual build jobs. Close and reopen works too if all of them failed spuriously.

**Comment by catherio** [comment]
The build with tensorflow 1.1.0 is now fine, but the 1.4.1 build is failing for reasons that look real. I'll see what I can do about that (https://github.com/tensorflow/cleverhans/issues/339).

**Comment by catherio** [comment]
Er, to clarify, I was wrong when I said tf 1.1.0 works "fine" - actually the build with 1.1.0 fails for a different reason, just much later in the process.

None of this has anything to do with your typofix obviously. Just happens to be revealing other issues that are preventing an auto-merge. I'll manually merge your change in a sec, and I've documented these build issues elsewhere.

**Comment by catherio** [comment]
Included in pr #343

**Pull request closed without merging**
