### PR TITLE
V4 structure

### PR DESCRIPTION
**Pull request by npapernot**
This is the proposed structure for working on the v4 of cleverhans. When the corresponding milestone is complete, we will reorganize the repository to have the structure defined in the main README

### CODE REVIEW

**Comment by npapernot** [comment]
cc @goodfeli

**Comment by david-berthelot** [comment]
Quick question: for tutorials there are no tf2/jax/torch folders, is it intentional?

**Comment by michaelshiyu** [comment]
@david-berthelot looks like there is?

**Comment by npapernot** [comment]
thanks I was missing the init files that's why

**Pull request merged**
