### PR TITLE
Add tutorial of CIFAR10 in TF2

### LINKED ISSUE #306: add CIFAR10 tutorial in TF2
This might require making some changes to the library to support this new mode.

### PR DESCRIPTION
**Pull request by souravsingh**
Fixes #306

### CODE REVIEW

**Comment by npapernot** [comment]
What's the accuracy before and after running the attack? The epsilon seems high (at least the default value of 0.3)

**Comment by souravsingh** [comment]
I will have to check, but I believe accuracy before the attack was around 75%

**Comment by npapernot** [comment]
This seems quite low. @david-berthelot do you think we could use your all convolutional model to get a better baseline?

**Comment by david-berthelot** [comment]
Yes reaching more than 90% should be relatively easy even with a small number of filters (say 16 or 32 for runtime reasons) for the all convolutional model already present in the current CleverHans. The code can be found here:
https://github.com/tensorflow/cleverhans/blob/master/cleverhans/model_zoo/all_convolutional.py

**Comment by npapernot** [comment]
I'm closing this PR because the code does not run (it is incomplete and needs to much work to be completed so starting from scratch in #1076)

**Pull request closed without merging**
