### PR TITLE
Check that image pixels are within [0.0, 1.0] bounds at the beginning of PGD attack

### PR DESCRIPTION
**Pull request by nottombrown**
Our PGD implementation requires that inputs are bounded to [0.0, 1.0]

We had a bug in data preprocessing that resulted in an input that was slightly out of bounds, this was hard to debug initially.

These assertions should help people track down the errors faster.

### CODE REVIEW

**Comment by npapernot** [comment]
Why does the implementation need the input to be bounded between 0 and 1?

**Comment by nottombrown** [comment]
It currently crops the output to be between 0 and 1, and then it checks that the perturbation is less than epsilon. 

If the initial input is less than 0 or more than 1, then it will always error out with a confusing assertion error.

**Comment by npapernot** [comment]
Tom and I discussed this offline and agreed to move the check within the `project_perturbation` helper before another PR addresses consolidation of the BIM, Madry and pgd_attack code snippets

**Comment by nottombrown** [comment]
Also adds a test that addresses #495

**Comment by goodfeli** [comment]
It seems strange to have a hardcoded range from 0.0 to 1.0. For other attacks, we have `clip_min` and `clip_max` parameters, and it's also possible to leave the clipping turned off. Is there a reason we can't have this attack match the others?

**Pull request merged**
