### PR TITLE
Update travis config in preparation for making certified defense.

### PR DESCRIPTION
**Pull request by AlexeyKurakin**
I have some problems making code for certified defense to be tested by Travis.
So I split the original change https://github.com/tensorflow/cleverhans/pull/723 into travis config and the code itself.

This is the first part of the change which only include updates in travis config

### CODE REVIEW

**Comment by goodfeli** [comment]
Yeah, let's drop support for older versions.

**Comment by AlexeyKurakin** [comment]
So do you want to drop support of both TF 1.4 and TF 1.8? and update everything to TF 1.9?
Or you still want to keep support of one of the older versions?

**Comment by goodfeli** [comment]
yeah, let's do 1.8 and 1.9 for now

**Comment by npapernot** [comment]
Just talked to Ian in real life and he agrees on dropping 1.4 and keeping 1.8

**Pull request merged**
