### PR TITLE
Added the bias to Conv2D in tutorial_mnist_tf

### PR DESCRIPTION
**Pull request by fartashf**
The bias was initialized but not used.

### CODE REVIEW

**Comment by fartashf** [comment]
The tests might need to be fixed because of this change. The model becomes stronger. Here are the numbers from `mnist_tutorial_tf.py` with `nb_epochs=50` before and after the change. There is a noticeable difference in the accuracy when the model is naively trained and tested against adversarial examples.

With Adversarial training
Legitimate examples:
Before: 99.23 +/- 0.03
After: 99.21 +/- 0.03

Adversarial examples:
Before: 98.45 +/- 0.12
After: 98.73 +/- 0.18

Without adversarial training
Legitimate examples:
Before: 99.31 +/- 0.03
After: 99.33 +/- 0.03

Adversarial examples:
Before: 11.67 +/- 2.06
After: 21.02 +/- 1.74

**Comment by npapernot** [comment]
Thanks for reporting these numbers. In order to have a fair comparison, we would have to run `tests_tf/test_mnist_tutorials_tf.py` (it runs on a subset of the training / eval data---because of the slow performance on Travis).

**Comment by goodfeli** [comment]
Pasting a few runs with the current version

**Comment by goodfeli** [comment]
`[INFO 2017-08-30 11:44:07,034 cleverhans] Epoch 0 took 1.00625705719 seconds
Test accuracy on legitimate examples: 0.9369
[INFO 2017-08-30 11:44:07,464 cleverhans] Epoch 1 took 0.397209882736 seconds
Test accuracy on legitimate examples: 0.9760
[INFO 2017-08-30 11:44:07,496 cleverhans] Completed model training.
Test accuracy on adversarial examples: 0.0060

Repeating the process, using adversarial training
[INFO 2017-08-30 11:44:09,616 cleverhans] Epoch 0 took 0.939763069153 seconds
Test accuracy on legitimate examples: 0.9339
Test accuracy on adversarial examples: 0.2763
[INFO 2017-08-30 11:44:10,654 cleverhans] Epoch 1 took 0.900452136993 seconds
Test accuracy on legitimate examples: 0.9610
Test accuracy on adversarial examples: 0.4895
[INFO 2017-08-30 11:44:10,786 cleverhans] Completed model training.
`

**Comment by goodfeli** [comment]
[INFO 2017-08-30 11:46:19,366 cleverhans] Epoch 0 took 0.946167945862 seconds
Test accuracy on legitimate examples: 0.9369
[INFO 2017-08-30 11:46:19,803 cleverhans] Epoch 1 took 0.39602804184 seconds
Test accuracy on legitimate examples: 0.9760
[INFO 2017-08-30 11:46:19,835 cleverhans] Completed model training.
Test accuracy on adversarial examples: 0.0060

Repeating the process, using adversarial training
[INFO 2017-08-30 11:46:22,008 cleverhans] Epoch 0 took 0.912930011749 seconds
Test accuracy on legitimate examples: 0.9279
Test accuracy on adversarial examples: 0.2763
[INFO 2017-08-30 11:46:23,026 cleverhans] Epoch 1 took 0.895193099976 seconds
Test accuracy on legitimate examples: 0.9580
Test accuracy on adversarial examples: 0.4835
[INFO 2017-08-30 11:46:23,142 cleverhans] Completed model training.

**Comment by goodfeli** [comment]
[INFO 2017-08-30 11:47:14,419 cleverhans] Epoch 0 took 0.911845207214 seconds
Test accuracy on legitimate examples: 0.9369
[INFO 2017-08-30 11:47:14,855 cleverhans] Epoch 1 took 0.399484872818 seconds
Test accuracy on legitimate examples: 0.9760
[INFO 2017-08-30 11:47:14,885 cleverhans] Completed model training.
Test accuracy on adversarial examples: 0.0090

Repeating the process, using adversarial training
[INFO 2017-08-30 11:47:17,006 cleverhans] Epoch 0 took 0.913484096527 seconds
Test accuracy on legitimate examples: 0.9279
Test accuracy on adversarial examples: 0.2823
[INFO 2017-08-30 11:47:18,040 cleverhans] Epoch 1 took 0.904149770737 seconds
Test accuracy on legitimate examples: 0.9610
Test accuracy on adversarial examples: 0.4955
[INFO 2017-08-30 11:47:18,172 cleverhans] Completed model training.

**Comment by goodfeli** [comment]
Now pasting a few before the change

**Comment by goodfeli** [comment]
[INFO 2017-08-30 11:48:37,116 cleverhans] Epoch 0 took 0.936095952988 seconds
Test accuracy on legitimate examples: 0.9369
[INFO 2017-08-30 11:48:37,536 cleverhans] Epoch 1 took 0.390725135803 seconds
Test accuracy on legitimate examples: 0.9790
[INFO 2017-08-30 11:48:37,562 cleverhans] Completed model training.
Test accuracy on adversarial examples: 0.0060

Repeating the process, using adversarial training
[INFO 2017-08-30 11:48:39,576 cleverhans] Epoch 0 took 0.887719869614 seconds
Test accuracy on legitimate examples: 0.9219
Test accuracy on adversarial examples: 0.2853
[INFO 2017-08-30 11:48:40,559 cleverhans] Epoch 1 took 0.872258901596 seconds
Test accuracy on legitimate examples: 0.9670
Test accuracy on adversarial examples: 0.4324
[INFO 2017-08-30 11:48:40,671 cleverhans] Completed model training.

**Comment by goodfeli** [comment]
Oh, actually the tests are based on train error, since we suspect it's more consistent

**Comment by goodfeli** [comment]
Printing out report.__dict__ for a few runs before the change

**Comment by goodfeli** [comment]
{'train_adv_train_adv_eval': 0.49120000000000003, 'train_adv_train_clean_eval': 0.95799999999999996, 'clean_train_clean_eval': 0.97897898953956164, 'adv_train_adv_eval': 0.43843843620102685, 'train_clean_train_adv_eval': 0.0118, 'train_clean_train_clean_eval': 0.97660000000000002, 'adv_train_clean_eval': 0.9669669753796345, 'clean_train_adv_eval': 0.0060060060032092414}

**Comment by goodfeli** [comment]
{'train_adv_train_adv_eval': 0.5, 'train_adv_train_clean_eval': 0.95940000000000003, 'clean_train_clean_eval': 0.97897897575710624, 'adv_train_adv_eval': 0.45045045143491153, 'train_clean_train_adv_eval': 0.0106, 'train_clean_train_clean_eval': 0.97619999999999996, 'adv_train_clean_eval': 0.9669669753796345, 'clean_train_adv_eval': 0.0060060060032092414}

**Comment by goodfeli** [comment]
{'train_adv_train_adv_eval': 0.47139999999999999, 'train_adv_train_clean_eval': 0.95860000000000001, 'clean_train_clean_eval': 0.97897898953956164, 'adv_train_adv_eval': 0.42042041710905126, 'train_clean_train_adv_eval': 0.010999999999999999, 'train_clean_train_clean_eval': 0.97619999999999996, 'adv_train_clean_eval': 0.9669669753796345, 'clean_train_adv_eval': 0.0060060060032092414}

**Comment by goodfeli** [comment]
Printing a few after the change

**Comment by goodfeli** [comment]
{'train_adv_train_adv_eval': 0.54259999999999997, 'train_adv_train_clean_eval': 0.96040000000000003, 'clean_train_clean_eval': 0.97597598546260111, 'adv_train_adv_eval': 0.49549549218412636, 'train_clean_train_adv_eval': 0.0118, 'train_clean_train_clean_eval': 0.97660000000000002, 'adv_train_clean_eval': 0.96396397130267397, 'clean_train_adv_eval': 0.0090090090062122444}

**Comment by goodfeli** [comment]
{'train_adv_train_adv_eval': 0.53300000000000003, 'train_adv_train_clean_eval': 0.96499999999999997, 'clean_train_clean_eval': 0.97597598546260111, 'adv_train_adv_eval': 0.48948949047395057, 'train_clean_train_adv_eval': 0.0114, 'train_clean_train_clean_eval': 0.97619999999999996, 'adv_train_clean_eval': 0.96996997838263754, 'clean_train_adv_eval': 0.0060060060032092414}

**Comment by goodfeli** [comment]
{'train_adv_train_adv_eval': 0.56159999999999999, 'train_adv_train_clean_eval': 0.95960000000000001, 'clean_train_clean_eval': 0.97597598546260111, 'adv_train_adv_eval': 0.50750750741801109, 'train_clean_train_adv_eval': 0.0124, 'train_clean_train_clean_eval': 0.97499999999999998, 'adv_train_clean_eval': 0.96096096829967093, 'clean_train_adv_eval': 0.0090090090062122444}

**Comment by goodfeli** [comment]
Based on these results, I'm tightening the tests

**Pull request merged**
