### PR TITLE
Fix logger messages

### PR DESCRIPTION
**Pull request by carlini**
A few minor fixes for the logger, changing messages in a few places to be slightly better. Also enable the logger for the tf example.

### CODE REVIEW

**Comment by npapernot** [comment]
Quick question: why did you add a condition on the l2 being smaller than `1e9`? 

Besides that LGTM

**Comment by npapernot** [comment]
You also have a pep8 pb: 

======================================================================
FAIL: Test if pep8 is respected.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/tensorflow/cleverhans/cleverhans/devtools/tests/test_format.py", line 45, in test_format_pep8
    raise AssertionError("PEP8 Format not respected")
AssertionError: PEP8 Format not respected
-------------------- >> begin captured stdout << ---------------------
/home/travis/build/tensorflow/cleverhans/tutorials/mnist_blackbox.py:206:1: W293 blank line contains whitespace
--------------------- >> end captured stdout << ----------------------

**Comment by carlini** [comment]
Eh. It's probably not the cleanest part of the code, but that's how I report success/failure. It initializes to 1e10 and "success" will mean less than that. Probably that should be fixed, because it's a fine assumption for image tasks (a distortion of ~200 max is possible on imagenet) but may not hold in general. I can deal with that in another PR.

**Comment by npapernot** [comment]
I see, this seems like a reasonable thing to do for now

LGTM

**Comment by goodfeli** [comment]
Looks like the travis bot had an internet connection problem. Can you push a dummy commit to trigger another travis build?

**Comment by carlini** [comment]
Done

**Comment by npapernot** [comment]
I restarted the Travis job that errored

**Pull request merged**
