### PR TITLE
load the pre-trained model

### PR DESCRIPTION
**Pull request by shenqixiaojiang**
The pull request is to address the problem of ["How to save and load model? #139"](https://github.com/tensorflow/cleverhans/issues/139)

### CODE REVIEW

**Comment by npapernot** [comment]
Ok now the CLA check passed, but the tests are broken because the tutorial should receive the flag values as optional arguments of the `mnist_tutorial` function and not through `FLAGS` directly.

**Comment by npapernot** [comment]
Why did you close this @shenqixiaojiang ?

**Comment by shenqixiaojiang** [comment]
Sorry,I'm new to the Pull Request of github. 
If the close operation had bad effect, I will be very sorry for this.

**Comment by goodfeli** [comment]
Thanks!

**Pull request merged**
