### PR TITLE
Moving a snippet of code to a better place

### PR DESCRIPTION
**Pull request by aashish-kumar**
As part of creating graph, None arguments are removed. This works as expected, but when generate_np is called in a loop, graph will be constructed only during first iteration. So further calls to generate_np can contain None arguments(as they were removed in function construct_graph) which result in following code to throw error:

`        for name in feedable:
             feed_dict[new_kwargs[name]] = feedable[name]`

None arguments should be removed for every call to generate_np so that a single class instantiation could be used.

### CODE REVIEW

**Comment by aashish-kumar** [comment]
@goodfeli I think there is some problem with the build setup. Can you please check?

**Comment by goodfeli** [comment]
Looks like the Travis build doesn't specify a version for `google-cloud`. I think this project got updated with an API-breaking change recently. I'm trying to fix this here: https://github.com/tensorflow/cleverhans/pull/482

**Comment by goodfeli** [comment]
The build is fixed now. I restarted the build for this PR.

**Comment by goodfeli** [comment]
@carlini can you review this one?

**Comment by aashish-kumar** [comment]
@carlini 
The problem is with calling `generate_np `multiple times in a loop. For the first iteration the `construct_graph ` will be called, it will not be called after that because of `hask_key`. All the other `generate_np `calls will have `kwargs` with some unused arguments too, which will not be deleted(deletion is part of `construct_graph`). These arguments throw errors while creating the feed_dict. I had proposed a remedy for that but I think removing it from construct_graph is not safe. 

I agree with you that removing unused arguments will cause errors when we call `construct_graph` from different paths where the deletion is not done. An alternative could be, to check for unused arguments while creating `feed_dict ` in this line. 
`         for name in feedable:
             feed_dict[new_kwargs[name]] = feedable[name]`

Also some paths could be using the unused arguments as control variable, so deletion in construct_variables is not safe.

**Comment by carlini** [comment]
Yeah, I understand the error case.

It seems like putting the deletion in `construct_graph` is where we want it, though, because not everyone uses `generate_np`. For example, if you use `generate` it still needs to delete the extra arguments.

**Comment by aashish-kumar** [comment]
I added a snippet in generate_np to fix the error without any modification to construct_graph. This will have minimum implications and still fixes the error.

**Comment by carlini** [comment]
Sounds good.

**Pull request merged**
