### PR TITLE
[WIP] Houdini Loss

### PR DESCRIPTION
**Pull request by vikramnitin9**
Implements a [Houdini](https://arxiv.org/abs/1707.05373)-based loss. The interface is a wrapper around an existing model and loss.

Related to issue #377.

TODO :
- [x] Make implementation more efficient
- [ ] Add tests
- [ ] Add examples

### CODE REVIEW

**Comment by goodfeli** [comment]
Is this still WIP or should I review / merge it?

**Comment by vikramnitin9** [comment]
Hi @goodfeli, could you take a quick look when you have the time, just to make sure I'm on the right track so far? I've tried out this implementation with the MNIST CW attack tutorial, and it seems to work.

However, it's far slower - 45 seconds per epoch vs 2.25 for the original implementation, on a GTX 1080 Ti. The main bottleneck seems to be the normal distribution survival function.

Also, it causes a slight drop in effectiveness of the attack (98 out of 100). This leads me to some questions about the formulation of the Houdini loss itself. If we want it to reduce to the task loss eventually, like the authors claim, shouldn't there be a factor of 2 multiplied with the stochastic margin? When the actual target is the same as the predicted target, the difference in scores is zero, and the margin is therefore 0.5.

When I multiply by this factor of 2 in my implementation (by adding a 2* [here](https://github.com/tensorflow/cleverhans/pull/967/files#diff-9c91717d5aff218520b49f838328f0f5R279)), I get 100 on 100 effectiveness again. What are your views on this?

**Comment by goodfeli** [comment]
Moustapha (1st author of the Houdini paper) works at Google now. I'll ask him if he can take a look.

**Comment by npapernot** [comment]
Hi @adiyoss could you take a look and provide some guidance? Would be great to have this loss merged!

**Comment by adiyoss** [comment]
Hi Nicolas,
Sure I would be happy to help :)
I’ll take a look at it later this week.

Y


On 5 April 2019 at 3:03:33, Nicolas Papernot (notifications@github.com)
wrote:

Hi @adiyoss <https://github.com/adiyoss> could you take a look and provide
some guidance? Would be great to have this loss merged!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/tensorflow/cleverhans/pull/967#issuecomment-480104928>,
or mute the thread

**Comment by npapernot** [comment]
Thanks a lot @adiyoss !

**Comment by npapernot** [comment]
@adiyoss gentle ping :)

**Comment by adiyoss** [comment]
Sure, I'll do it soon, sorry for being late. A little busy with finalizing my PhD dissertation :)

**Comment by npapernot** [comment]
No problem @adiyoss, did you get a chance to look at this recently?

**Comment by npapernot** [comment]
Closing due to inactivity, feel free to reopen if you keep working on the PR. Thanks!

**Pull request closed without merging**
