### PR TITLE
fix ead bug

### PR DESCRIPTION
**Pull request by ysharma1126**
relatively recent push caused an issue with EAD, this fixes it.

### CODE REVIEW

**Comment by goodfeli** [comment]
The PEP8 tests are failing

**Comment by goodfeli** [comment]
Needs a rebase

**Comment by ysharma1126** [comment]
Rebase done.

**Comment by ysharma1126** [comment]
Can this fix be pushed soon?

**Comment by nottombrown** [comment]
Lgtm. Squashed and merged

**Pull request merged**
