### PR TITLE
closes #243

### LINKED ISSUE #243: The `stop_gradient` op in FastGradientMethod is wrong
The `stop_gradient` op in FastGradientMethod should only be present for the max norm and in that case it should wrap only the sign op, not the addition of the perturbation to the input. The `stop_gradient` op should reduce computational cost but should not change the numeric value of any derivatives.

### PR DESCRIPTION
**Pull request by goodfeli**

### CODE REVIEW

**Comment by goodfeli** [comment]
Note: besides fixing the tests, I should also:
- make sure the tutorials that do adversarial training add the stop_gradient themselves. That part should probably be optional
- check how the other attacks handle stop_gradient

**Comment by goodfeli** [comment]
OK, I did the things in my previous comment.

**Comment by npapernot** [comment]
LGTM, thanks for renaming the variable names in `fgm`, they are more consistent now.

**Comment by npapernot** [comment]
LGTM, ready to merge

**Comment by goodfeli** [comment]
Do you know what went wrong with @googlebot ?

**Comment by npapernot** [comment]
It usually goes into this mode every time someone pushes to a contributor's branch that is not under tensorflow/cleverhans but in a fork.

**Comment by goodfeli** [comment]
If I merge the PR, will it make the build show up as broken because of the failing googlebot test?

**Comment by npapernot** [comment]
No, the build shows broken only if the Travis tails fail. The googlebot test is just shown on PRs

**Comment by goodfeli** [comment]
OK, since we know the CLA is actually signed, I'll ignore Googlebot and merge

**Pull request merged**
