### PR TITLE
Addition of RLAttack to examples

### PR DESCRIPTION
**Pull request by behzadanksu**
RLAttack added to examples. 

RLAttack is an interface between Cleverhans and OpenAI Baselines for experimenting with adversarial example attacks on deep Reinforcement Learning. Current version supports FGSM, Iterative, and CWL2 attacks on DQNs. 

Thanks to Nicolas Papernot for suggesting this PR on cleverhans-dev .

### CODE REVIEW

**Comment by behzadanksu** [comment]
Signed CLA

**Comment by behzadanksu** [comment]
@npapernot @goodfeli I would appreciate your review on this :)

**Comment by npapernot** [comment]
In the PR, I see that you are not merging any source code but rather including one of your repository as a submodule of the CleverHans repository. Is that correct? If yes, is the repo you are trying to link to this one: https://github.com/behzadanksu/rl-attack

**Comment by catherio** [comment]
I would quite strongly advise against adding a submodule to cleverhans without a major reason to, which I haven't yet seen. The section "The dangers we face" in this medium post explains my thinking: https://medium.com/@porteneuve/mastering-git-submodules-34c65e940407

Other options include importing rlattack as a package and including an example script showing how it's used, or merging the code into this repository.

**Comment by goodfeli** [comment]
Thansk for the warning, @catherio . Based on that medium post, I think it would be better to have an example in the examples directory that imports the rlattack as a package. The README for the example can give the user instructions for how to download and install rlattack.

**Comment by goodfeli** [comment]
I'll close this version of the PR but you're welcome to reopen a version that doesn't use a submodule

**Comment by behzadanksu** [comment]
@goodfeli @npapernot @catherio @yenchenlin  Thank you for your comments, and apologies for my late response. Following your suggestions, I am preparing an example script with a detailed README file, and will submit another PR soon.

**Pull request closed without merging**
