### PR TITLE
changed all intances of num_classes to nb_classes

### LINKED ISSUE #766: number of classes parameters
Make sure the name of the parameter used for the number of classes is consistent throughout the library. Parts of the code use nb_classes and others num_classes

### PR DESCRIPTION
**Pull request by robert-wagner**
fixes #766

### CODE REVIEW

**Comment by robert-wagner** [comment]
Tests failed during autenticating pep8. Will fix and push

**Comment by goodfeli** [comment]
Thanks for your contribution.

CleverHans has a policy of giving a warning when APIs change, so that people have up to 6 months to change to the new interface. This means we need to support the old parameter name, and then use an if statement inside the function to tell whether the caller passed the old version.

You can see an example of how I changed the `epsilon` argument to `eps` for the `SPSA` class in this recent PR: https://github.com/tensorflow/cleverhans/pull/833/files

**Comment by robert-wagner** [comment]
Thank you for the reference for how to update. I will go back through and update it properly

**Comment by goodfeli** [comment]
Thank you!

**Comment by robert-wagner** [comment]
Assuming travis passes, it should be fixed now for backwards compatibility.  num_classes is still in the code base whenever inception is used as the parameter for that is num_classes

**Comment by robert-wagner** [comment]
Hi is there a standard linter or way to run all of the tests that travis runs locally? I would love to add this to the readme to ease development

**Comment by AlexeyKurakin** [comment]
You can run following commands to run all tests:
```
# runs linter and some of the cleverhans tests, usually pretty quick
nosetests -v --nologcapture --stop cleverhans
# runs tests, which actually train models and run attacks, slow
nosetests --nologcapture -v --stop tests_tf
```

You will need to have some additional dependencies installed for this to work:

* nosetests
* joblib
* pylint

You can take a look at https://github.com/tensorflow/cleverhans/blob/master/.travis.yml to see what travis actually doing when running tests.

**Pull request merged**
