### PR TITLE
Rename test_attacks.py -> test_vat.py

### PR DESCRIPTION
**Pull request by carlini**
As suggested in PR 156.

### CODE REVIEW

**Comment by carlini** [comment]
Looks like the build failed due to a HTTP read timeout, so everything should be fine here.

**Comment by npapernot** [comment]
I restarted the test

**Comment by aam-at** [comment]
The idea is to have all attack tests in one file. It follows a standard python convention where tests for module file are located in `test_<file_name>`. Imho, I don't think that having tests in one will make things unmanageable.

**Comment by npapernot** [comment]
That's fair, I'll close it in that case and delete my comment from #156

**Pull request closed without merging**
