### PR TITLE
Better canary

### PR DESCRIPTION
**Pull request by goodfeli**

### CODE REVIEW

**Comment by goodfeli** [comment]
I forgot to put it in the commit messages, but this closes #795

**Comment by carlini** [comment]
I know you've been having issues with this a lot, but is this a common enough issue to warrant adding it to cleverhans?

**Comment by goodfeli** [comment]
Anyone in our group using CleverHans for multi-GPU workloads will encounter it somewhere between once per day and once per week. It's hard to tell how much it will affect people in other labs without access to their hardware. If it does affect other group's experiments, it's likely to do so by silently introducing wrong results into their evaluation benchmarks.

**Comment by carlini** [comment]
I see, okay.

**Pull request merged**
